INSERT INTO HOTEL (ID, NAME) VALUES (1, 'Marriot');
INSERT INTO HOTEL (ID, NAME) VALUES (2, 'Radisson');
INSERT INTO HOTEL (ID, NAME) VALUES (3, 'Hardrock');
INSERT INTO HOTEL (ID, NAME) VALUES (4, 'Sterling');
INSERT INTO HOTEL (ID, NAME) VALUES (5, 'Le meridian');